### ISSUE TITLE
[Critical] Unable to Join Private Session with More than 20 Members

### ISSUE THREAD

**Issue by m-amarillas** [coolfiresolutions/core-service-desk#74] opened 2021-04-12 17:21 UTC
**Describe the bug**
American Expediting has Sessions with 30+ users. We are getting reports of Drivers getting permissions error's when trying to open the Session. I noticed that we are only showing the top 20 users in the list, so my assumption is that our permission checks are only pulling in the top 20 users, which is giving the false error that they do not have permissions.

Screenshot of the error are attached.

**Where are you seeing this?**
All

**To Reproduce**
1. Create a Session with more than 20 users

**Screenshots**
![Image from iOS (2)](https://user-images.githubusercontent.com/53492670/114435324-a79f6c80-9b89-11eb-9ad3-7d18bd529675.jpg)

![Screen Shot 2021-04-12 at 12 18 45 PM](https://user-images.githubusercontent.com/53492670/114435291-9f473180-9b89-11eb-9737-0cf0e3234ae7.png)

**Comment by cfsbhawkins** [comment] 2021-04-12 17:24
@m-amarillas Is this on all devices or just iOS?

**Comment by m-amarillas** [comment] 2021-04-12 17:25
All devices.

**Comment by cfsbhawkins** [comment] 2021-04-12 17:26
So Web too?

**Comment by m-amarillas** [comment] 2021-04-12 17:28
I personally have not seen it on Web. I have had reports of users getting an infinite spinning when clicking into a Session on web, which could be related to this bug.

**Comment by cfsnkajok** [comment] 2021-04-12 17:45
@m-amarillas , just to clarify, you've reproduced this on Android and iOS? But now web?

**Comment by m-amarillas** [comment] 2021-04-12 17:54
These are reports I'm getting from the field. My account is not able to reproduce on Web, but I have received reports of users getting an infinite spin wheel when clicking into a Session. It may or may not be related.

The issues on Mobile are the ones getting reported frequently.

**Comment by cfsnkajok** [comment] 2021-04-12 17:55
Okay thanks, we're investigating on all interfaces now.

**Comment by cfsnkajok** [comment] 2021-04-12 18:23
We believe we understand the root cause of the issue. We will begin working on a hotfix.

**Comment by cfsbhawkins** [comment] 2021-04-13 16:41
This has been hotfixed closing.

**Closed by cfsbhawkins** 2021-04-13 16:41 UTC
